### ISSUE TITLE
Edit tab: Import Failed Help button doesn't fit when task bar location on screen is top

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1355]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1315) by aki.sivula on 16 Dec 2013_

Minor glitch on UI -&gt; Edit tab: Import Failed Help button doesn't fit when task bar location on screen is top. See attachment.

Python 2.7.5
wx: 2.8.12.1

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1315#c1) by aki.sivula on 17 Dec 2013*


RIDE 1.2.3

**Comment by Nyral** [comment]
@HelioGuilherme66 I don't see any problem on Windows. Maybe it's on some other OS?
There's also no attachment to know exactly the original issue was about :(

**Comment by HelioGuilherme66** [comment]
When we are at test suite level the Edit screen shows the Library, Resources, Variables, etc. If we expand the Settings panel, those buttons (in particular the ones below Variables button), would disappear. Because there is no vertical scroll bar, they become inaccessible. Collapsing Settings would make them visible again.

Would be to much coding work to fix this usability issue.
  
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
