### ISSUE TITLE
Robot code in reStructuredText format support

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1447]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1407) by cristian... on 21 May 2015*

Robot framework supports
- HTML format
- TSV format
- Plain text format
- reStructuredText format

Currently, RIDE does not support reStructuredText format (rst extension).

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1407#c1) by cristian... on 21 May 2015*


In 1.4a1 version, you can edit rst files, but if you added more text (some title and description, for example), all changes are lost when saving.

**Comment by yanne** [comment]
This is because the writer modules of Robot Framework itself, which RIDE uses for saving, do not support writing `.rst` files. I do not think we have resources to implement this support. However, if we ever implement generic text editing support, this will be partially resolved then.

Closing this for now, though.
