### ISSUE TITLE
Run tab contains no show logfile button

### ISSUE THREAD

**Issue by michel117** [robotframework/RIDE#1465]
Probably this is not a bug, but an enhancement.
On Windows RIDE provides a show logfile button in order to open logfile after test execution easily.
This button does not exist in RIDE for MacOS and would be a feature enhancement.

**Comment by jerry57** [comment]
I hate to say this, but if there  is a "feature" in one platform, shouldn't that "feature" be in ALL platforms?  Unless it is platform specific.  I don't think that displaying the logfile would qualify for "platform specific".  This doesn't sound like an enhancement but rather a bug.

**Comment by yanne** [comment]
I agree with @jerry57. However, the buttons are there, but the labels for some reason are not, so they are more difficult to find.
![screen shot 2015-06-09 at 19 35 45](https://cloud.githubusercontent.com/assets/159146/8063687/ef4b3c8c-0ede-11e5-9094-dddea0d9c6bd.png)

So the bug is actually missing labels, which is consider quite minor.

**Comment by michel117** [comment]
Hello @yanne  ! You are so right! 
I found the buttons and want to apologize to file such a minor issue.
