### ISSUE TITLE
Misleading error message when run with wxPython3

### ISSUE THREAD

**Issue by Twoflower2** [robotframework/RIDE#1481]
On Debian 8 RIDE 1.4 complains:

"You need python-wxgtk2.8.12.1 or newer ....."

The thing is I have python-wxgtk3.0 which is newer.

Please fix this incorrrect dependency check!!

**Comment by Twoflower2** [comment]
( wxPython3.0 (python-wxgtk3.0) does not need python3. It will work fine with Python 2.6 and 2.7 - 32 and 64 bit. On our Debian box python-wxgtk3.0 works with Python 2.7 )

**Comment by HelioGuilherme66** [comment]
RIDE is not compatible with wxgtk3, you must use the recommended version
that you received the warning.

There are different function calls in newest wxgtk.

I you want to fork RIDE and send a pull request, we all would thank you a
lot!!

**Comment by Twoflower2** [comment]
The warning is "You need python-wxgtk2.8.12.1 or newer ....." and python-wxgtk3.0 is python-wxgtk2.8.12.1 or newer :-)

**Comment by Twoflower2** [comment]
Also when is RIDE expected to be compatible with wxgtk3? Some rough idea is good. Latest Debian does not have wxgtk2 in its repos and other Linux Distro will surely go that way too.

**Comment by HelioGuilherme66** [comment]
From the instructions (WIKI
<https://github.com/robotframework/RIDE/wiki/Installation-Instructions#wxpython>),
you have:
<https://github.com/robotframework/RIDE/wiki/Installation-Instructions#wxpython>
wxPython
<https://github.com/robotframework/RIDE/wiki/Installation-Instructions#id8>

RIDE's GUI is implemented using wxPython <http://wxpython.org/> toolkit.
Only *wxPython 2.8.12.1* with Unicode support is officially supported.
Possible new releases in wxPython 2.8 series ought to work fine too.
wxPython 3.0 support is one of the priorities for future development.

---

Future development means: Who knows? :D

**Comment by yanne** [comment]
1) You are correct that the error message is extremely misleading, and should be changed.
2) Currently, as fas as I know, I am the only person maintaining RIDE. I have a couple of weeks worth of sponsored time to work on it until the end of September. After that, I'll probably only be able to respond to issues and merge pull requests, but won't be able to do any meaningful development. It's highly unlikely that I'll be able to finish the wxPython3 support, since the more urgent issue is supporting RF2.9

I have an experimental branch,https://github.com/robotframework/RIDE/tree/wxPython3-compatibility, which addresses some of the compatibility issues, but not likely all. Any feedback on the branch is much appreciated.

**Comment by Twoflower2** [comment]
@HelioGuilherme66 - Thanks
@yanne - Thanks for the nice honest reply and I wish I had time to help. I'll help to give feedback.

**Comment by yanne** [comment]
I changed the title, since there is already an issue about wxPython3 compatibility.
