### ISSUE TITLE
Cannot import remote library in 1.4.1

### ISSUE THREAD

**Issue by claytonneal** [robotframework/RIDE#1503]
Hello.
I have RF version 2.8.7 installed
When i install RIDE 1.4.0 i can import a remote library
When i install RIDE 1.4.1 i CANNOT import a remote library, the error given is:

20150817 16:24:58.769 [WARN]: Importing test library "Remote" failed

Traceback (most recent call last):
Importing test library 'Remote' failed: ImportError: No module named Remote
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Python27\lib\site-packages\robotide\lib
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  C:\Windows\system32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\robotide\spec
  .
  C:\Python27\lib\site-packages\robotide\spec\remote
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 41, in TestLibrary
    libcode = importer.import_class_or_module(name)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 64, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 99, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by jongu82** [comment]
I had a similar issue to this and @yanne advised me that due to a change in RF2.9, you will have to edit your import statement from "import remote" to "from robot.libraries import remote"

**Comment by claytonneal** [comment]
Ok thanks for the info. So is the issue in ride or in robot framework itself?

**Comment by jongu82** [comment]
The issue appears to be with Robot Framework.  Versions prior to 2.9 put robot.libraries into pythonpath by default.  With 2.9 and newer, the long path is now required.  @yanne explained this to me on gitter

**Comment by yanne** [comment]
@claytonneal Do you have the option `Use installed robot libraries` in `Tools | Preferences | Importing` checked or not? Does changing the value resolve this problem?

**Comment by MichaelHallik** [comment]
@yanne I am having the same issue, since I upgraded to 1.4.1 (as of today).

 I have jrobotremoteserver running, serving a test class I wrote. The 'remote' library import statement in RIDE is red. And the RIDE log is printing the error as mentioned in the first post above (by @claytonneal ).

However, RF actually IS executing the relevant test cases. They are run successfully.

Can you please tell me what I need to do to get the import statement in RIDE to be black again? :-)

I have a meetup as well as a conference work-shop coming up (in which I am supposed to be evangelizing RF & RIDE), and I would like to not have any red import statements. :-)

Tnx a lot in advance! Regards, Michael

**Comment by claytonneal** [comment]
hiya, downgrading to RIDE v1.4.0 worked for me
pip install robotframework-ride==1.4.0

**Comment by MichaelHallik** [comment]
Hi @claytonneal 

Thank you for your reply.

One more question: which version of RF do you have installed?

I have v2.9 right now. I am quite worried that downgrading might break other stuff.  See e.g. https://github.com/robotframework/RIDE/issues/1476.

I never had 1.4 installed, so I don't know whether it is stable/reliable. :-)

**Comment by claytonneal** [comment]
I downgraded that also to 2.8.7

**Comment by MichaelHallik** [comment]
@claytonneal : OK, tnx a lot!

@yanne : I do not whether this additional info will help (or whether you knew this all along), but:

As mentioned above: the RF (2.9 in my case) itself apparently imports the remote lib just fine, since the keywords as implemented in my test class (running in the jremoteserver) run just fine.

Maybe you could give a quick work-around (as an alternative to downgrading). Next week I am also giving several days of training and I would like to use the latest RF version. Tnx in advance!

**Comment by HelioGuilherme66** [comment]
One way to solve the red indication of imported libraries is to add the
spec file (XML). If the tests run OK, that means only is missing the
keywords documentation.

**Comment by MichaelHallik** [comment]
@HelioGuilherme66 

Thank you for the reply.

I do indeed use spec files for several testing libraries that I am using. For instance for the RemoteSwingLiband and for my own Java test classes (that I run locally).

However, do I also need spec files for the standard RF libraries? Or do you mean that a spec file for the remote library may work as a temporary work-around?

Thanks again,

Michael

**Comment by HelioGuilherme66** [comment]
Try to add the spec for RemoteSwingLibrary.

For example, even for BuiltIn I add to import the library to have the
documentation in RIDE.

**Comment by MichaelHallik** [comment]
@HelioGuilherme66 
Tnx again. Should I try something like this:

python C:\Python27\Lib\site-packages\robot\libdoc.py -f XML C:\Python27\Lib\site-packages\robot\libraries\Remote.py C:\Demos\Test_libraries\_Spec_files\Remote.xml

?

**Comment by yanne** [comment]
@MichaelHallik Run libdoc.py --help. It contains an example of creating spec file from a remote library. And you need to name it Remote.xml for this workaround.

I am working on a fix to this whole mess. It's partially complete, and I will release 1.5 alpha 2 as soon as it's ready. 

If the problem is only a remote library, downgrading to 1.4 should be a viable option, even if you have RF 2.9 installed.

**Comment by MichaelHallik** [comment]
@yanne : Tnx! I have two possible work-arounds now. :-)
