### ISSUE TITLE
Inserting code in robotframework test data editor

### ISSUE THREAD

**Issue by peacechan** [robotframework/RIDE#1547]
Can we insert code (python, bash, ruby etc..) into the ride.py text editor? If so any example or tutorial to follow?
Or is there any other way to write code into it?

**Comment by yanne** [comment]
Currently this is unfortunately impossible. This has been in the backlog for a long time, but there are currently no one working on it, AFAIK.

**Comment by Nyral** [comment]
@HelioGuilherme66 Just a question. No point in keeping it open.

**Comment by HelioGuilherme66** [comment]
Since 1.7.3 we can edit other files.

Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
