### ISSUE TITLE
Sort trailing numbers in tag names numerically in View All Tags

### ISSUE THREAD

**Issue by alexisbietti** [robotframework/RIDE#1579]
Related to enhancement #1527

Sort by tag name does a simple text comparison, which gives weird results when tag names have trailing numbers:

![2016-01-26 16_42_42-clipboard](https://cloud.githubusercontent.com/assets/220144/12585349/f9e3af62-c44b-11e5-8c79-10d64460c1cb.png)

This can be enhanced by parsing the tag name and considering any trailing number as a numeric value before sorting:

![view all tags](https://cloud.githubusercontent.com/assets/220144/12585054/9fffa6b4-c44a-11e5-9f52-ba952c0d08e1.png)

[SortTagByTrailingNumber.txt](https://github.com/robotframework/RIDE/files/105164/SortTagByTrailingNumber.txt)

**Comment by HelioGuilherme66** [comment]
I did the PR #1580 using your code, since it is not available at your fork.
Tested with file at [Tags_test.robot](https://dl.dropboxusercontent.com/u/50838335/Robot%20Files/Tags_test.robot)

**Comment by pekkaklarck** [comment]
I'm not sure is this a good idea. What about leading or intermediate numbers? A simple workaround for this problem is adding leading zeros like `Sprint-01`.

**Comment by yanne** [comment]
I don't like this either, for the reasons @pekkaklarck mentioned. This opens up a door for supporting all the possible positions for numbers, which is a bit more complex case.

**Comment by alexisbietti** [comment]
I don't mind if I'm the only one using this little modification. I agree the general case of supporting any position of number is really complex and not worth the effort. But trailing incrementing number are the norm in issue trackers such as Jira, and these tools don't insert leading zeroes to every past issue each time a new digit is reached just to fix sorting. Cheers.

**Comment by alexisbietti** [comment]
By the way, thanks for taking the time to enter the PR @HelioGuilherme66 .

**Comment by HelioGuilherme66** [comment]
Comparison of the Tag Sorting feature.
In the folowing images we compare the After and Before the code changes.
![after 1580_a](https://cloud.githubusercontent.com/assets/2866630/12833522/2754edea-cb99-11e5-9e16-4c403979dcd7.png)
after#1580_a.png - A - prefix numbering sorted numerically (ignores leading zeroes)
                   B - prefix numbering sorted alphanumerically (considers leading zeroes)
![after 1580_b](https://cloud.githubusercontent.com/assets/2866630/12833526/3334e638-cb99-11e5-9f30-11c348320c0a.png)
after#1580_b.png - A - suffix numbering sorted numerically
                   B - suffix numbering sorted alphanumerically
![after 1580_c](https://cloud.githubusercontent.com/assets/2866630/12833534/3e35b530-cb99-11e5-9b06-8a632c139706.png)
after#1580_c.png - A - inner numbering sorted numerically (ignores leading zeroes)
                   B - inner numbering sorted alphanumerically (considers leading zeroes)
                       Note outstanding "Rand17om10" in B case.
![after 1580_d](https://cloud.githubusercontent.com/assets/2866630/12833541/4af0cb5c-cb99-11e5-85c7-d8c68c959e5e.png)
after#1580_d.png - A - suffix numbering sorted numerically
                   B - suffix numbering sorted alphanumerically
                       Note interference of symbols " -#" in B case.
![after 1580_e](https://cloud.githubusercontent.com/assets/2866630/12833544/53879fca-cb99-11e5-9690-a61a46491fde.png)
after#1580_e.png - (same case as previous)

I think that this PR is a good improvement, and does not have negative impact, 
because this is only a visual representation. We will have a better sorted list.

I have updated the test file at [Tags_test.robot](https://dl.dropboxusercontent.com/u/50838335/Robot%20Files/Tags_test.robot)

Please accept merging this.
Thanks.

**Comment by pekkaklarck** [comment]
I'm still not a big fan of this idea. One problem I see is that it would be weird for RIDE to sort tags specially if Robot Framework doesn't do that.

**Comment by yanne** [comment]
This sorting only affects the dialog 'View all Tags`. Hence, I am inclined to include this, since this is mainly a usability feature. The easier it is to find a tag, the more useful the dialog is.

**Comment by yanne** [comment]
@HelioGuilherme66 Can you update the PR, and possibly also add the test case file you used under `utest/resources/robotdata/`. It's probably not worth it to try to make an unit test for this, but having the example file could still be useful.

**Comment by HelioGuilherme66** [comment]
@yanne I added the test file. I'll see if I can create unit tests, because they are needed (there is a bug in the test selection and search by tag, I will create issue soon).

**Comment by HelioGuilherme66** [comment]
Already done since 1.7.3
