### ISSUE TITLE
Find Usages not working for variables definitions

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#1605]
If we right click in a cell having a variable definition or assignment there should show a choice dialog.
(the dialog is not shown and goes strait to results, if there is no = sign)
This is the dialog after the fix (coming in a PR soon):
![find_usage_variable_definition_ok](https://cloud.githubusercontent.com/assets/2866630/13206530/7d2377ee-d8f7-11e5-8c2a-64aeb771775e.png)

**Comment by HelioGuilherme66** [comment]
I am going to propose a PR with the following solutions:
- Removed repeated variable names from cell content but keeping occurrence order
![find_usage_variable_definition_ok1_dialog](https://cloud.githubusercontent.com/assets/2866630/13289434/f119f18e-db07-11e5-9ce7-dca9b40868a6.png)

- There is a bug in the dialog which prevents to show the '&' in dictionaries (but results are OK). I opted to show \x26{varname} instead of just {varname}.
![find_usage_variable_definition_ok_results](https://cloud.githubusercontent.com/assets/2866630/13289450/013533e4-db08-11e5-8a2e-ad64eaac38b2.png)

**Comment by yanne** [comment]
wxPython Controls (`wx.Control` subclasses, which `wx.RadioBox` is) have a feature of using ampersands to define mnemonics. You can escape the ampersand with a second (i.e. `&&` will render one ampersand). You could also use http://wxpython.org/Phoenix/docs/html/Control.html#Control.EscapeMnemonics method to escape all labels. I think the latter would be best, since then you don't have to manually search the ampersands.

**Comment by HelioGuilherme66** [comment]
I tried all those options. It just happens that `wx.RadioBox` does not allow to escape the ampersand. I was not able to override `wx.RadioBox`, to use own SetString for the `choices` parameter. Please help me figuring out this,

**Comment by yanne** [comment]
Fixed by #1606
