### ISSUE TITLE
Sometime report and logs button get disabled after test run (selenium)

### ISSUE THREAD

**Issue by vvvvaib** [robotframework/RIDE#1627]

**Comment by vvvvaib** [comment]
Frequently faced with an issue where after running a test case - Report and log buttons remain "disabled". If I close RIDE at this time- it hangs and then I have to kill ride.py from cmd. 

Extra info- @HelioGuilherme66 has also seen the same issue. Seems like "It happens mostly with Windows and when using Selenium2Library (probably not closed the webdriver or some fault happened)."

**Comment by StefanIGit** [comment]
So it is a Selenium2Library problem? Is Selenium closed (java process)?

**Comment by JediMaster93** [comment]
@StefanIGit 
This happens to me to and I dont use selenium.
Copy pasting the .xml path into browser manually works

**Comment by HelioGuilherme66** [comment]
The buttons get disabled when processes started by robot/TestRunner keep the lock of the output file. If it is webdriver, killing it (on any OS) would make the buttons active.

There isn't much we can do about this.

Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
