### ISSUE TITLE
Extract keyword functionality doesn't add the arguments to the new created keyword

### ISSUE THREAD

**Issue by andrefrescata** [robotframework/RIDE#1644]
Extract keyword functionality doesn't add the arguments of the keywords that are called the newly created keyword. We have to go into each keyword and add its arguments to the new keyword.

**Comment by Nyral** [comment]
That's because Extract Keyword is intended to create a new keyword with rows you have selected.
For creating keyword with arguments, as mentioned in title, there is Create Keyword.
![2019-05-24_03-20-55](https://user-images.githubusercontent.com/39315668/58294486-0a8b8d00-7dd3-11e9-9ac3-0c5c3c5cb0aa.png)

@HelioGuilherme66 Invalid. Can be closed.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):

- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
