### ISSUE TITLE
importing library DebugLibrary and running project makes .rbt file compleetly unusable

### ISSUE THREAD

**Issue by macakmujo** [robotframework/RIDE#1645]
git clone https://github.com/robotframework/QuickStartGuide.git

open with RIDE
import DebugLibrary
run tests

**Comment by HelioGuilherme66** [comment]
This happens because the initial opened file is modified by the Import insertion.
The Use Case you mention should be a corner case, because the .rst file will loose all non Robot Framework text (better use a specific .robot file). However if you save the file and then open it in RIDE, it will run OK. If you edit QuickStartGuide.rst and add after line 311 `    Library           DebugLibrary` then the file will run OK too.

The fix I would propose, is to recommend saving the file with a .robot extension when the user runs tests in a .rst file.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
