### ISSUE TITLE
How to build the RIDE Source code

### ISSUE THREAD

**Issue by ArunPachauri** [robotframework/RIDE#1671]
Hello,
I am new on this forum and learning python.

I want to apply some changes in RIDE Source code.
Downloaded Path - https://github.com/robotframework/robotframework

Can you please let me know step by step how to do this ?

Thanks
Arun P

**Comment by HelioGuilherme66** [comment]
Well, this is an Issue tracker, not a Forum.
You should learn GitHub processes, then Fork RIDE project see the "Fork me" button on the <> Code section. Then clone it on your system. Python programs are not build, they are just run from source code (but they could be installed). See the README, and the Wiki.
(Please close this Issue, because it is not a real one.)

**Comment by ArunPachauri** [comment]
Sorry Mr. Helio for mistake.
Thanks.
