### ISSUE TITLE
robotframework 3.0 running isn't stable

### ISSUE THREAD

**Issue by wohuyuelong** [robotframework/RIDE#1675]
My environment is：Windows 10 64-bit family Chinese version; python2.7; ff45.6.0; robotframework 3.0

When I use Robot Framework 3.0 for end-to-end acceptance testing,the result is fail,but the script is not wrong. Without any changes,but replay-repaly,somethimes the result is pass!

**Comment by HelioGuilherme66** [comment]
This Issue tracker is for the RIDE (Robot Framework Integrated Development Editor). The problem you mention is not related with this Editor.
Are you sure the problem is with robotframework, and not with another imported Library, like for example Selenium2Library?
Should your test cases rely on timings and so they are "brittle"?
Maybe you should ask for help in Slack or StackOverflow, and please provide specific information on which keywords the tests fail.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
