### ISSUE TITLE
ride - HTTP [Error 403] : Must access using HTTPS instead of HTTP

### ISSUE THREAD

**Issue by DavidSGH** [robotframework/RIDE#1692]
Hi.

I am new with this.

Recently I install robotframework (3.0.2), robot-framework-selenium2library(1.8.0), wxPython(2.8.12.1) and ride(1.5.2.1) on Windows 10.

When I execute the command `ride.py` this shows the following:

**Creating librarykeywords database to "C: \ Users \ dsgonzalez \ AppData \ Roaming \ RobotFramework \ ride \ librarykeywords.db"
HTTP Error 403: Must access HTTPS instead of HTTP**

Ride runs, but I have this message on console that I would like to be able to solve, because I do not know if it can affect future functionality.

Thanks guys!

**Comment by HelioGuilherme66** [comment]
I suspect that you get that error because RIDE is trying to check for updates with old protocol.
You can confirm this by running RIDE like this:
`ride.py --noupdatecheck`

Then you can edit the file "C: \ Users \ dsgonzalez \ AppData \ Roaming \ RobotFramework \ ride \ settings.cfg", and set:
`check for updates = False`

You can also fix the URL on file: `C: \ Python2.7 \ Lib \ site-packages \ robotide \ application \ updatenotifier.py`

I also think you can fix by upgrading `urllib2` like:
`pip install --upgrade urllib3`

Good luck
(@yanne or @pekkaklarck would need to merge fixes, but they have been away from this project)

**Comment by DavidSGH** [comment]
Thanks @HelioGuilherme66  I solved this issue.
