### ISSUE TITLE
ImportError: No module named 

### ISSUE THREAD

**Issue by DavidSGH** [robotframework/RIDE#1694]
Hi guys.

I´m trying do an example from this page:

> http://blog.mykhailo.com/2011/02/how-to-sikuli-and-robot-framework.html

My config is this:
robotframework: 3.0.2
robotframework-ride: 1.5.2.1
python: 2.7

I make a file .bat with this settings:
```
@echo off
set sikuli_jar=C:\Robotframework_Sikuli\Utils\sikulix.jar
set pythonpath=c:\Robotframework_Sikuli\Scripts\Calc\

java -cp "C:\Robotframework_Sikuli\Utils\robotframework-3.0.jar;%sikuli_jar%" ^
     -Dpython.path="%sikuli_jar%/Lib" ^
     org.robotframework.RobotFramework ^
     --pythonpath=Calc.sikuli ^
     --outputdir=results ^
     --loglevel=TRACE ^
%*
```

Where 'Robotframework_Sikuli' is my main folder. 
'Utils' contain java standalone, robotframework.jar and sikuli.jar. 
and 'Scripts' contain the `.sikuli` folder, `.bat`, and `.txt`.

My file 'Calc.py' is a copy from this.

> https://gist.github.com/imikemo/806544#file-calc-py

And my Test Case . txt is this.

```
*** Settings ***
Library           Calc

*** Test Cases ***
Verify that 2 + 2 = 4
    Start App
    Verify App
    Perform Action    2    +    2
    Verify Result    4

Verify that 2 + 2 = 5
    Start App
    Verify App
    Perform Action    2    +    2
    Verify Result    5
```

But, When i run this TestCase in Ride, i have this Error:

`[ ERROR ] Error in file 'C:\Robotframework_Sikuli\Scripts\Calc\verify_operations.txt': Importing test library 'Calc' failed: ImportError: No module named Calc
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\WINDOWS\SYSTEM32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
`

Anyone could help me??

Thanks

**Comment by DavidSGH** [comment]
I do a little change in my .bat file. 

I set the PythonPath like this:
`set pythonpath=C:\Robotframework_Sikuli\Scripts\Calc.sikuli\Calc.py`

and in my file .py rename the Class with the same name that my file .py
**Calc**

So, I got a new trace Error:
```
[ ERROR ] Error in file 'C:\Robotframework_Sikuli\Scripts\Calc\verify_operations.txt': Importing test library 'C:\Robotframework_Sikuli\Scripts\Calc\Calc.sikuli\Calc.py' failed: ImportError: No module named org.sikuli.basics
Traceback (most recent call last):
  File "C:\Robotframework_Sikuli\Scripts\Calc\Calc.sikuli\Calc.py", line 2, in <module>
    from sikuli.Sikuli import *
  File "C:\Robotframework_Sikuli\Utils\Lib\sikuli\__init__.py", line 5, in <module>
    from org.sikuli.basics import Debug
PYTHONPATH:
  C:\Robotframework_Sikuli\Utils\Lib
  C:\WINDOWS\SYSTEM32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
Log:     c:\users\dsgonz~1\appdata\local\temp\RIDE2brk98.d\log.html
Report:  c:\users\dsgonz~1\appdata\local\temp\RIDE2brk98.d\report.html
```

But I dont know how import this library from sikuli. I try using Python via cmd with this syntax:
`from org.sikuli.basics from Debug`
in **Lib/sikuli**
and I get the same error:
```
File"<stdin>", line 1, in <module>
File "sikuli\__init__.py", line 5, in <module>
  from org.sikuli.basics import Debug
ImportError: No module named org.sikuli.basics
```

Any comment??

**Comment by HelioGuilherme66** [comment]
These are my comments:
1. Your problem is not with RIDE (and this is an Issue tracker), you should have asked on our Google Group, Slack channel or even StackOverflow/StackExchange.
2. There is a comment in the end of the blog, by Sikuli maintainer referring to [another helpful site](http://blog.mykhailo.com/2011/02/how-to-sikuli-and-robot-framework.html).
3. There is another RobotFramework-Sikuli library with an easier setup at [robotframework-SikuliLibrary](https://github.com/rainmanwy/robotframework-SikuliLibrary).
4. Remember that when using Java is best to define the CLASSPATH env var pointing to the jar files in use. This is very important for RIDE to see libraries when running with Jython (jybot).
5. You are trying to call robot from the 3.0 jar, not from python (don't mix them).
6. Did you have success in running in Sikuli IDE? And from the python example?
7. The URLs you posted are redirecting to Issue pages (not found), please try to edit them. Thanks.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
