### ISSUE TITLE
Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open

### ISSUE THREAD

**Issue by Naseem126** [robotframework/RIDE#1706]
When I am running test in Chrome, they are fine. But if I change the browser to ie, the test fails with this feedback:
 
"[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open"

I googled for a solution but did not find any. Thanks in advance for providing solution.

OS: Windows 7 Pro
RIDE 1.5.2.1 running on Python 2.7.13.

**Comment by HelioGuilherme66** [comment]
This problem is not related with RIDE. It is related to Selenium or Selenium2Library not finding the browser or it was closed. This depends if the message appears at start, or near the failed keyword.
(did it connected to IEDriverServer?)
This is not a bug, and the test did not failed with that message because it is just a warning.

Please close this issue. Thanks.

**Comment by Naseem126** [comment]
You are right. This is issue with ie settings . Thanks
