### ISSUE TITLE
Ride does not serialize anchors for test cases and keywords anymore

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#171]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=136) by @yanne on 13 May 2009_

In 0.13, an anchor was created for each td containing a keyword name.
This is no longer done.

**Comment by HelioGuilherme66** [comment]
Well, a feature that stopped working since 0.14, and we are now on 1.7.3, does not look that important. Furthermore, the HTML format is deprecated in current `robot` 3.1.1.

Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
