### ISSUE TITLE
How to check code supporting test library's keywords

### ISSUE THREAD

**Issue by malbertone** [robotframework/RIDE#1737]
Hi,
was trying to debug an issue (reported already in https://github.com/robotframework/RIDE/issues/1736).
Think the issue is in the code supporting a keyword which looking at the RIDE search keyword window is defined as:

Name: Load Configurations
Source: RobotSPS <test library>
Arguments: [ config_file | verification_flag=None ]

Since I'm not the developer of the library would like to know at least, and in general terms, where to find the test library the Source is referring to. I have a folder named RobotSPS in 
C:\Python27\Lib\site-packages\RobotSPS

but could not find any file including that definition.

I've seen that for user keywords I get reported a source file I could look into for the code, but for library ones there's not such file so that I assume it may be in a class file or similar, could you help me with that?

Thanks
Mike

**Comment by 0xLeon** [comment]
This is probably not a thing to ask in the RIDE repository, more of a general Robot Framework question. Something like StackOverflow would be the better place to ask.

Anyway, the thing you have to look into is the folder you found. In general, this doesn't have to be a folder. A keyword library is part of a Python package usually named the same as the library. This can be a plain Python file as well. A simple `import RobotSPS; help(RobotSPS)` should reveal the basic library structure. If it's a library not using the dynamic API, you will see the keywords directly as class methods. If it's a dynamic API library, things do get a little tricky, because you can't just look up the keywords and the associated method. For furhter information on how a keyword library is built, see the [Robot Framework documentation on creating keyword libraries](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-test-libraries).

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
