### ISSUE TITLE
can not be installed in python 3.5

### ISSUE THREAD

**Issue by Moriand** [robotframework/RIDE#1756]
Hello hello, it's a good application, I want to have it but it turns out that it can not be installed in python 3.5

**use pip install**  
 Microsoft Windows [Versión 6.3.9600]

C:\Windows\system32> **pip install robotframework-ride**
Collecting robotframework-ride
  Using cached https://files.pythonhosted.org/packages/3c/14/a5f97f5cf5e981f01e8
c0b4c405b0dfc9bc86500cabb044d2c462f73004a/robotframework-ride-1.5.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DennM\AppData\Local\Temp\pip-install-ig339_j7\robotframew
ork-ride\setup.py", line 20, in <module>
        execfile(join(ROOT_DIR, 'src', 'robotide', 'version.py'))
    NameError: name 'execfile' is not defined

**Comment by HelioGuilherme66** [comment]
Hi, I mentioned my [fork ](https://github.com/HelioGuilherme66/RIDE)because this project has been not updated in a year.
You can install from releases or clone and try from there. Please see the Wiki because there are known bugs, which I register there.
(I would recommend upgrading python to 3.6)

Please close this issue.
