### ISSUE TITLE
RIDE listener doesn't seem to be working when using custom script

### ISSUE THREAD

**Issue by Hi-Fi** [robotframework/RIDE#1797]
RIDE version: 1.5.2.1 and 1.7.3
Python version: 2.7.15
OS: Windows 10
Example project: https://github.com/Hi-Fi/robotframework-java-example
Relates to: Hi-Fi/robotframework-java-example#1

With old version listener is usable also for tests running with custom script (in this case Maven). 
![image](https://user-images.githubusercontent.com/1499780/51531812-24c65600-1e47-11e9-80bd-77beee1d9c16.png)

With latest version, error is thrown and nothing is coming to listener section:
![image](https://user-images.githubusercontent.com/1499780/51531824-2d1e9100-1e47-11e9-9a89-54dfed404841.png)

Between the images only change was to install RIDE 1.7.3 (and it's dependencies).

**Comment by pekkaklarck** [comment]
The listeners tries to do `from robotide.utils import PY2, PY3` which requires `robotide` module (i.e. RIDE itself) to be installed on that interpreter that is used for running tests. Can be fixed by avoiding such dependencies on the listener side. In this case `PY2` and `PY3` constants are easy to create based on `sys.version_info` in the listener itself.

**Comment by Hi-Fi** [comment]
Listener seemed to be working fine, thank you.
