### ISSUE TITLE
tests name can not contains "[]"(RIDE 1.7.4dev1 and older)

### ISSUE THREAD

**Issue by dujihui1983** [robotframework/RIDE#1965]

**Comment by dujihui1983** [comment]
![图片](https://user-images.githubusercontent.com/15654028/60512209-8e0b9880-9d06-11e9-9da3-12523c534120.png)

**Comment by Soothsilver** [comment]
Starting from Robot Framework 3.1, brackets are part of simple patterns when selecting test cases: https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#wildcards 

> [abc] matches one character in the bracket.

I don't think there is a way to run specifically those tests, because you can't escape characters when selecting test cases. RIDE doesn't have a way of asking Robot Framework to run just this test:

> Although test case names can contain any character, using ? and especially * is not generally recommended because they are considered to be wildcards when selecting test cases. For example, trying to run only a test with name Example * like --test 'Example *' will actually run any test starting with Example.

**Comment by dujihui1983** [comment]
thanks！

**Comment by HelioGuilherme66** [comment]
Thanks @Soothsilver for the research (I think that documentation was improved with a PR of mine ;) ).
@dujihui1983 Closing this because there is not much RIDE can do, and Robot Framework, Rules!
