### ISSUE TITLE
I can't open the keyword Editor

### ISSUE THREAD

**Issue by zhiyinyouzhao** [robotframework/RIDE#1995]
when I open the ride, I I can't open the keyword Editor.
Then view the RIDE.log. I find some thing.
please help me .thanks!

20190906 09:47:08.034 [ERROR]: Error in listener: The C++ part of the KeywordEditor object has been deleted, attribute access no longer allowed.
While handling <robotide.publish.messages.RideSettingsChanged object at 0x0000000021B33D68>

Traceback (most recent call last):
The C++ part of the KeywordEditor object has been deleted, attribute access no longer allowed.
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotide\publish\publisher.py", line 84, in __call__
    self.listener(event.data)
  File "D:\Program Files (x86)\Python27\lib\site-packages\robotide\utils\eventhandler.py", line 21, in wrapped
    if self._can_be_edited(event):
  File "D:\Program Files (x86)\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 14619, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)

**Comment by HelioGuilherme66** [comment]
@zhiyinyouzhao You did not gave info about the environment you are using, so now I have to make some questions:
- I see you are using Python 2.7 and wxPython 2.8.12.1 in Windows with 64bit, but you installed 32bit versions. Why not install the 64bit versions?
- How did you install RIDE and what is the version?
- Did you installed RIDE for the first time on this system? Or did you used it before?
- What were you doing when the problem was registered on log?
  (looks like you were editing Tools>Preferences)

**Comment by HelioGuilherme66** [comment]
Closing because is too old and we cannot reproduce, or lack of information.

**Comment by Francine10291995** [comment]
Hello Po,
Can you help me with this? https://prnt.sc/qz0znt 
I'm new to Robot Framework. Thanks

**Comment by HelioGuilherme66** [comment]
@Francine10291995 Asking for help on Closed issues, is very unlikely to have success.

There are many wrong things on your installation. You should see the Release Notes for version 1.7.4.1 (go to the Code tab here on this project and read the README).

You should ask questions on Slack, Google Groups, Stack Overflow. The issue tracker is to report problems.
