### ISSUE TITLE
The "\" in :For loop will disappear after restart ride

### ISSUE THREAD

**Issue by shenjianyun** [robotframework/RIDE#2041]
i use robot framework 3.1.2, robot framework-ride 1.7.3.1 on mac os 10.14.5
when write for loop like:
:FOR 
              XX
              XX
when run test case will give waring message "**Escaping empty cells with '\' before line continuation marker '...' is deprecated. Remove escaping before Robot Framework 3.2.**"
then i change the for loop format to:
:FOR 
\         XX
\         XX

The warning message will disappear when modified all the for loop in every robot file
But when restart the ride, all the modified  were in vain

**Comment by HelioGuilherme66** [comment]
@shenjianyun On that RIDE version you will see the deprecation warning and lose your changes. Since it is only a warning there will not be major problems. If you install newer RIDE pre-release versions for 1.7.4, you will have your edited file modified, but causing a major problem, because the `:FOR` must be changed to `FOR` & `END` block. So if you install a newer RIDE you must be aware of this problem. Please see our [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.#2-q-in-the-newest-versions-of-ride-174-and-with-robot-framework-312-when-i-edit-a-test-suite-having--for-then-when-is-executed-appears-the-following-error-for-loop-contains-no-keywords-how-to-fix-this).
