### ISSUE TITLE
How do I make multiple versions of ride coexist?

### ISSUE THREAD

**Issue by mdks2010** [robotframework/RIDE#2151]
The problems I am currently facing are:
The original test case was based on Python2 and was written on the 1.5.2.1 version of the ride.
Currently planning to write a new test case based on Python3 in ride1.7.4.1,

In order to reduce the impact on the previous case, I originally planned to install ride1.7.4.1 in a virtual environment, run the ride.py in the “ \ venv \ Scripts \”  directory to enter the 1.7.4.1 version, but it is still non-virtualized every time I open it Version 1.5.2.1 of the environment and is based on Python2.

How do I set up to run the latest version of ride based on Python 3 in a virtual environment?

Remarks:
I created the virtual environment through pycharm and installed the latest RIDE。

**Comment by HelioGuilherme66** [comment]
@mdks2010 There are several issues on this setup. First, you mentioned that the virtual environment was created via PyCharm. I don't know about that, I would install Python3 normally and then create the virtual env (that would not be needed anyway).

The launcher of RIDE but be prepared to run the correct installation. So, you would need to create a .cmd file to start the virtual env, defne the PATH and PYTHONPATH to point to the correct `robot` and libraries. Additionally, you can add the PYTHONPATH in the Tools->Preferences.

There may be problems when using different RIDE installations, because they share the same configuration file at `%AppData%\Roaming\RobotFramework\ride\settings.cfg`.

My advise is to install Python3 normally and RIDE and `robot` in it. The only problematic issue with newer RIDE, is the `:FOR` not being used anymore. You can even open python files in a basic code editor.
