### ISSUE TITLE
Resource files disappearing after editing in Text Edit mode

### ISSUE THREAD

**Issue by emilezwiggelaar** [robotframework/RIDE#2162]
I noticed this new 'feature' in RIDE v1.7.4.1 where, after updating resource files in Text Edit mode, they every now and then just disappear in RIDE.

To reproduce I've 

1) Created a very small project with just one testsuite folder and file and a resource folder and resource file. Both with .robot extension.
2) Then I edit the resource file, any edit will do and save the project 
3) And then I edit the same file again and save again.

Result is that the resource file disappears in RIDE and the project needs to be reopened to get the file back.

If you edit a testcase in between then the resource file won't disappear.

**Comment by HelioGuilherme66** [comment]
This issue is probably already known from the many issues about resources. You can use this [search](https://github.com/robotframework/RIDE/issues?q=is%3Aissue+is%3Aopen+resource) and observe that the refreshing of the use of resources has been reported. Even so, I will keep this report active.

**Comment by HelioGuilherme66** [comment]
Attaching recording of the issue.
[ExternalResource disappears.zip](https://github.com/robotframework/RIDE/files/4372181/ExternalResource.disappears.zip)

**Comment by yuanzhiyu000x** [comment]
This problem is still unresolved in RIDE 1.7.4.2 .

**Comment by HelioGuilherme66** [comment]
@yuanzhiyu000x We know. There are no differences in 1.7.4.2 and 1.7.4.1.

**Comment by jnhyperion** [comment]
I think this issue should be fixed with this PR:

https://github.com/robotframework/RIDE/pull/2232

The modification actions probably triggered the previous file content change event watcher.

@HelioGuilherme66 your video shows the similar scenario, the only difference is you were using external resource.

If that external resource is not imported in your project, any workspace reloading will make it disappear. That's reasonable, because RIDE does not know where's your external resource unless you import it.
