### ISSUE TITLE
Not able to save test case in RIDE

### ISSUE THREAD

**Issue by Gaurav21git** [robotframework/RIDE#2250]
I am using Python 3.6 version with below software. When i try to save a test case in RIDE, it throwing exception. Please provide support to fix this issue.

![image](https://user-images.githubusercontent.com/43947717/88391024-f9734d00-cdd6-11ea-8502-d05577c062a4.png)

![image](https://user-images.githubusercontent.com/43947717/88390930-d47eda00-cdd6-11ea-8882-5ec6a8c6f6e8.png)

**Comment by HelioGuilherme66** [comment]
@Gaurav21git Please make sure you can create files on the root of system disk (C:\). Windows may be preventing you to do this.
Use other program, like for example Notepad, and create a new file there.

This issue have been reported in the past, and I suppose it is fixed in 1.7.4.2, or the newer v2.0b1.
