### ISSUE TITLE
UI: Give clearer message for run when not test is selected

### ISSUE THREAD

**Issue by halperinko** [robotframework/RIDE#2329]
UI: Give clearer message for run when not test is selected
Currently the message just says that no test was selected and asks to continue or not,
But does not indicate that in case we continue (press OK) All tests will be selected to be run.

Also - while allowing this option from preferences serves the ability to run all test cases,
It might be clearer to add a Select All icon,
Which can also ease cases where user wants to select many but not all test cases, then its easier to click Select All and unselect specific ones.

**Comment by HelioGuilherme66** [comment]
Before this option, the all test would be run without warning. It was added to prevent clicking Run or F8 by distraction and thus running all tests.
Then some user complained that would not like to see that Dialog, so we added the switch on the Preferences.

I am inclined to reject your request, because it is the user responsibility to select the tests prior to run them (an now has a warning if did not select any).

If you make a code proposal, I may reconsider, but this would be a low-priority. We have many other issues and features to do.
