### ISSUE TITLE
RIDE snap install

### ISSUE THREAD

**Issue by ksokolowski** [robotframework/RIDE#2373]
Hello.

Taking into account all dependency hell we have, when installing RIDE under Linux, is there any plan to migrate (un)official releases to be prepared as snaps?
https://snapcraft.io/

**Comment by HelioGuilherme66** [comment]
No.
I disagree of using special package managers to install RIDE.
We used to have a dedicated installer for Windows.

I personally don't like Snap not Flatpack.
My usual systems are RPM based, so I would use `dnf`, `yum`or `zypper`. For Debian based would be `apt-get`.
For MacOS would be  `homebrew` (also possible for Linux).
On Windows we could use `chocolatey`.

My decision is to use `pip` because it is common for all systems.

The *hell* you mention can be minimised, by proper `pip` setup and dependencies management.
Maybe you feel the need for better documentation, and it can be done on our Wiki.
