### ISSUE TITLE
workspace modification detected on the file system

### ISSUE THREAD

**Issue by Raguramt** [robotframework/RIDE#2394]
Whenever I change application RIDE is showing showing workspace modification detected on the file system Do you want to reload the workspace?

**Comment by HelioGuilherme66** [comment]
@Raguramt This has been observed by me too, on my system, Fedora 34, with Python 3.9, and wxPython 4.1.1,
The directory structure opened in RIDE is a Git project, and I had at the same time the PyCharm IDE opened. More information on debugging this is needed, because I don't know if it is sufficient the fact of being a Git project, or if is necessary to have some app using the same project, or a specific app like PyCharm.

What you can do is:
- Provide information about your operating system, and versions,
- Confirm if the RIDE project was opened as a directory/folder, of an isolated TestSuite (a single .robot file),
- Confirm that some other IDE, like PyCharm was opened at the same time and accessing the same directory

Experiment, to only open a single TestSuite in RIDE, and repeat the actions in attempt to reproduce the case.

This is very important to identify the root cause, so that we can improve RIDE.

Thanks.

**Comment by HelioGuilherme66** [comment]
@Raguramt Please see if current master improves the situation. Thanks.
