### ISSUE TITLE
run ride,log error:No keyword with name 'TRY' found

### ISSUE THREAD

**Issue by zhangys1989** [robotframework/RIDE#2488]
Starting test: Suit1.
20220916 15:23:15.731 :  FAIL : No keyword with name 'TRY' found.

No keyword with name 'BuiltIn.TRY' found.

python version 3.10.0
wxpython version 4.2.0
ride version is master code

robotframework 5.0.1
robotframework-appiumlibrary 1.6.3
robotframework-databaselibrary 1.2.4
robotframework-pythonlibcore 3.0.0
robotframework-ride 2.0b2.dev23
robotframework-selenium2library 3.0.0

![tryerror](https://user-images.githubusercontent.com/41988543/190582619-2934d20b-dbb4-45bc-b670-354721c2da32.jpg)

**Comment by zhangys1989** [comment]
@HelioGuilherme66 can you help me

**Comment by HelioGuilherme66** [comment]
@zhangys1989 Here are my comments:
The output in Console and Log panels comes from the execution of roibot, so it is very unlikely that the problem is from RIDE.
You should take a look at log.html to better locate the error.
There is a selected test case named `${EMPTY}`, this may have been caused by a RIDE bug (sometimes empty lines in Grid Editor go replaced by the ${EMPTY} variable). You should delete that line, because may be cause of error.
Other thing can be that RIDE is not really running `robot version 5.0.1`. RIDE runs the first `robot` it finds on $PATH.
To clarify this, you should show me the output of RIDE->Tools->View RIDE log.

Question:s: 
- is your system Linux or Mac?
- did you personalize the colors?

Thanks.

**Comment by zhangys1989** [comment]
my system is Mac@HelioGuilherme66
