### ISSUE TITLE
[Grid Editor] Mouse wheel scrolling of the Grid Editor is not working

### ISSUE THREAD

**Issue by ZDabrowski** [robotframework/RIDE#2875]
Scrolling using the mouse wheel is working on the Text Editor window, Test suite tree window, File tree window but not for the Grid Editor window.

**Environment**
Python 3.10.12
wxPython 4.2.1
robotframework 6.0.2
robotframework-ride 2.1.dev75
Ubuntu 22.04.4 LTS
LXDE

**Comment by HelioGuilherme66** [comment]
@ZDabrowski Could it be LXDE?
Now the scroll bars are for the whole Grid Editor page, not for the rows and columns as it used to be. You may need to have the mouse pointer over the scroll bar.

In my Fedora 40 with KDE Plasma 6 they work.

**Comment by ZDabrowski** [comment]
@HelioGuilherme66, it's similar on the LXDE - when the mouse pointer is over the scroll bar it's working properly, otherwise it's not scrolling.
Surely, the more user-friendly behaviour would be scrolling regardless of the position of the mouse pointer (excel style) :)

**Comment by Roboteus** [comment]
I have the same and other thing with scrolling which doesn't work is functionality to scroll by selecting rows by LMB pushed on:
![image](https://github.com/user-attachments/assets/55374235-896c-4fa2-b529-3a4d59f43414)

Windows 11
Python 3.11.9
wxPython 4.2.1
robotframework-ride 2.1.dev73

**Comment by Roboteus** [comment]
installing new wxPython didn't help
pip install -i https://test.pypi.org/simple/ wxPython==4.2.2a1

installing RIDE version v2.1dev75 didn't help

**Comment by HelioGuilherme66** [comment]
Fixed in v2.1.dev76.
Unknown origin of the following side-effect:
- After expanding Settings in Test Cases or Keywords, and collapsing, the scrolling stops working. To recover the correct scrolling, you should select another Test Case or Keyword, and return to the affected item.

**Comment by ZDabrowski** [comment]
@HelioGuilherme66, after your fix in v2.1.dev76 the scrolling is not working on the Grid Editor.
Checked Suite settings - scrolling ok.
Checked test cases and keywords, with and without expanded Settings - mousewheel scrolling is not working.
There's not even a slider on the right to move it.
Please, check it.

By the way - panning the view by moving the active cursor (`Page Up`, `Page Down` or arrows) also does not work in Grid Editor.

**Environment**
Python 3.10.12
wxPython 4.2.1
robotframework 6.0.2
robotframework-ride 2.1.dev76
Ubuntu 22.04.4 LTS
LXDE

**Comment by HelioGuilherme66** [comment]
@ZDabrowski That is the side-effect I mentioned. Unless it happens differently in your environment.
I have written a question on [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.#22-q-using-development-version-21dev76-env-fedora-linux-40-with-kde-plasma-6-python-3125-wxpython-421-after-expanding-settings-in-test-cases-or-keywords-and-collapsing-the-scrolling-stops-working-by-using-keys-and-not-possible-to-use-scroll-bars-because-they-disappear-how-to-solve-this)

**Comment by ZDabrowski** [comment]
I've installed 2.1dev78 and it's working partially on my environment.

I suppose the key is the `Grid Editor Settings`:
- Use fixed widht font - **enabled**
- Default column size: 150
- Auto size column - **disabled**
- Word wrap and auto size rows - **disabled**

When I create a new test case, the scrollbar appear when the number of filled rows do not fit in the window. Then the mousewheel scrolling is working properly.
After reopening this test case (go to the other testcase and return), the scrollbar is missing and the scrolling is not working. Adding new lines does not trigger the scrollbar to appear.
However, noticed that resizing of the row manually triggers the scrollbar to appear and the mousewheel scrolling works but, as mentioned in the previous comment, is still limited and cannot reach the last rows.

The situation changes for the better when `word wrap and auto size rows` is **enabled**.
Then, the only situation when the scrollbar disappears is after changing the window size (maximize, manually resize).
But the solution for that case was given in the FAQ.

@HelioGuilherme66 do you have an idea for this?

**Environment:**
Python 3.10.12
wxPython 4.2.1
robotframework 6.0.2
robotframework-ride 2.1.dev78
Ubuntu 22.04.4 LTS
LXDE

**Comment by HelioGuilherme66** [comment]
@ZDabrowski I recommend for you (and all), to try to upgrade wxPython to 4.2.2 (just released this week). Although this problem still exists after the upgrade.

I know the parts of the code that are affected by this. The change I did to have the full Setting expanded at **Test Suite** level, creates the scroll bars in the top pane (the Notebook area). But then the expanding and collapse of the Settings at **Test Case** or **Keyword** level, makes the automatic scroll bars in the Grid area to disappear. Unfortunately, this is not just the scroll bars, but also the keys use (arrows, tab, enter), that does not makes the current cell visible.

Because the main fix for the **Test Suite** level, is more important than this problem, I plan to leave as it now. Users, shall be aware of this problem and workaround (select other test case or keyword).

**Comment by HelioGuilherme66** [comment]
@ZDabrowski I have now limited the scrolling changes to Linux systems. It will not solve your case, but it should be easier for Mac and Windows users.

@Roboteus Please test again in v2.1de79.

Thanks.

**Comment by HelioGuilherme66** [comment]
Changed again in v2.1dev81.
Behavior equal for all OS. 

**Scrolling of Grid by using arrows keys, stops working after changing Settings collapsed/expanded**

**Comment by Roboteus** [comment]
doesnt work again in 2.1.1
