### ISSUE TITLE
[Grid Editor] Resizing between "Test suites" area and "Editor" is impossible

### ISSUE THREAD

**Issue by Roboteus** [robotframework/RIDE#2876]
![image](https://github.com/user-attachments/assets/8589ef54-e6ca-47a3-9ff2-a5918df3b9db)

Windows 11
Python 3.11.9
wxPython 4.2.1
robotframework-ride 2.1.dev73

**Comment by HelioGuilherme66** [comment]
@Roboteus I don't have Windows 11 to try RIDE, but I suspect the GUI problems you are finding may be related to it.
Can you please try to install wxPython 4.2.2 (alpha)? I know that somethings work on it (at least on Fedora 40).

You may also use a `virtualenv` so that you don't change your usual setup.

**Comment by Roboteus** [comment]
installing new wxPython helped
pip install -i https://test.pypi.org/simple/ wxPython==4.2.2a1
