### ISSUE TITLE
[Grid Editor] arguments values can be recognized as keywords

### ISSUE THREAD

**Issue by Roboteus** [robotframework/RIDE#2878]
![image](https://github.com/user-attachments/assets/edf20cf9-0f44-4617-b382-a5bc5fb31668)

Windows 11
Python 3.11.9
wxPython 4.2.1
robotframework-ride 2.1.dev73

**Comment by HelioGuilherme66** [comment]
@Roboteus Colorization of cells is a complex thing, and in the case the arguments are also keywords, it colorizes as keywords.

In the below image, you can see both cases, where one argument is not keyword and the other is:
![image](https://github.com/user-attachments/assets/ae5c0256-63e0-4a81-83fe-12a8ba723da4)

Please Upgrade your development version of RIDE, because there are some fixes and maybe new bugs ;).
You can use the `Help->Check for Upgrade` function.

**Comment by Roboteus** [comment]
yes this "Description" in my case it is real keyword so seems that it's not a bug

**Comment by JFoederer** [comment]
Yes, for me this is an important feature. I use inline keywords (or keywords as arguments a lot) and RIDE really helps. It is the only editor I know that does this.
