### ISSUE TITLE
[QUESTION] How to Skip `__init__` execution during RIDE Checking?

### ISSUE THREAD

**Issue by AndresSanchez229** [robotframework/RIDE#2915]
Hello guys,

This is not an issue at all, perhaps a question on how to proceed.

**Introduction:**
I am using Robot Framework for hardware validation. It requires some equipment drivers that we are creating or adapting for Robot Framework. Some of the things we are doing during the library `__init__` function include checking the compatibility version of the driver (this is an internal checking) and recognizing all compatible equipment connected to the PC. This works fine for Robot Framework CLI.

**Issue description:**
The issue is that this feature makes the execution slower for RIDE because it runs the `__init__` method at the beginning of the execution, after reloading the project, and in other cases. It shows some pop-ups and spends some time trying to recognize all compatible equipment.

**Question:**
1. Would it be possible to add some instructions in `__init__` to skip the initialization just for RIDE checks and execute it properly during Robot Framework test execution? 

2. I would like to keep the driver version checking because it is useful to see if there is an error when I include that library in RIDE. Would that also be possible?

I have tried with these lines, but it still shows some pop-up messages as if it were running the recognition steps:
```python
try:
    test_suite_name = BuiltIn().get_variable_value('${TEST NAME}')
    if test_suite_name is None or len(str(test_suite_name)) == 0:
        return 
except Exception as e:
    return
```

**Comment by HelioGuilherme66** [comment]
@AndresSanchez229 This could be some special case for an enhancement request for RIDE.

Is the `__init__` you mention only the definition in your `own` library? Or is it also a Roibot Framework file (`__init__.robot`) in the project? 

If it is a `__init__.robot`, you can try to add to the *excluded* files.

If is only in you library, then I doubt RIDE can do anything about it, unless it is really just importing it to discover the keywords.
But if you are seeing its execution, it means that you are running the test cases (so, it does not make sense your code experiment, because TEST NAME always exists).

My approach to solve this, is to define an environment variable when running from RIDE (with a batch or shell script file), and then your library bypasses its execution.

**Comment by AndresSanchez229** [comment]
Hello @HelioGuilherme66,

Thanks for your comments. I was facing some problems with updating the library. I thought I was updating the library with my code experiment, but I was running the older version. Sorry for the misunderstanding.

From my side, the experiment code works because it returns an exception if we run the library outside of the Robot Framework scope. This is exactly what I want to do. By catching the exception, I can detect if the library has been initialized by Robot Framework test execution or from RIDE internal checking.
