### ISSUE TITLE
Tooltip with named arguments is confusing

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#774]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=739) by @mkorpela on 11 Mar 2011_

Example:

Keyword  some value  name=value  [Tooltip here is giving wrong info!]

**_Keywords**_
Keyword
  [Arguments]  ${somevalue}  ${unused}=Default  ${name}=Defa  ...

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=739#c2) by @jussimalinen on 6 Nov 2012*


As a clarification: tooltip shows the argument name "${unused}" as name for the field "name=value" in above example. This can be confusing.

This however is not very critical. setting priority to low.

**Comment by Nyral** [comment]
@HelioGuilherme66 Does this make any sense for you?

Tooltip looks like this currently:
![pythonw_2019-05-22_21-40-08](https://user-images.githubusercontent.com/39315668/58199958-4abb1480-7cda-11e9-84d2-0db057fabfab.png)

I don't think this issue exists anymore.

**Comment by HelioGuilherme66** [comment]
@Nyral They were referring to the tool tip for arguments. See below:
![image](https://user-images.githubusercontent.com/2866630/58291630-01d88e00-7db6-11e9-8dd9-f3f5dcf4d0c1.png)

Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)

**Comment by Nyral** [comment]
@HelioGuilherme66 I see, in that case this is an issue. Please reopen it.

**Comment by HelioGuilherme66** [comment]
@Nyral No, it was an issue when it showed "${unused}".

**Comment by Nyral** [comment]
@HelioGuilherme66 Ah... yes. I understand now, sorry.
